services:
  storage:
    image: minio/minio
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - ./data/storage:/data
    command: server /data --console-address ":9001"

  app:
    depends_on:
      - storage
    build: .
    environment:
      DB_PATH: /data/todo.db
    ports:
      - 8080:8080
    volumes:
      - ./litestream.local.yml:/etc/litestream.yml
